name: main workflow

on:
  push:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.7.24-management-alpine
        ports:
          - 5672:5672

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install project dependencies
        run: make setup

      - name: Run security check
        run: make check-sec

      - name: Run code quality
        uses: olxbr/code-quality-action@v1

  build-and-publish:
    if: startsWith( github.ref, 'refs/tags/' )
    needs: [quality]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install project dependencies
        run: make install && python3 -m pip install build

      - name: Choose tag or commit as version
        id: release
        uses: olxbr/tag-or-commit-action@v0.0.10

      - name: Build package
        env:
          RELEASE_VERSION: ${{ steps.release.outputs.version }}
        run: python3 -m build -s

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
