name: main workflow

on:
  push:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.7.24-management-alpine
        ports:
          - 5672:5672

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install project dependencies
        run: make setup

      - name: Run security check
        run: make check-sec

      - name: Run code quality
        uses: olxbr/code-quality-action@v1

  build-and-publish-dev:
    if: startsWith( github.ref, 'refs/tags/' )
    needs: [quality]
    runs-on: ubuntu-latest
    environment: 'dev'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install project dependencies
        run: make install && python3 -m pip install build

      - name: Build package
        run: python3 -m build -s

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

  publish-prod:
    if: startsWith( github.ref, 'refs/tags/' )
    needs: [quality, build-and-publish-dev]
    runs-on: ubuntu-latest
    environment: 'prod'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install project dependencies
        run: make install && python3 -m pip install build

      - name: Build package
        run: python3 -m build -s

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
