name: main workflow

on:
  push:
  workflow_dispatch:

jobs:
  quality:
    runs-on: ubuntu-latest

    services:
      rabbitmq:
        image: rabbitmq:3.7.24-management-alpine
        ports:
          - 5672:5672

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install project dependencies
        run: make install

      - name: Run security check
        run: make check-sec

      - name: Run code quality
        uses: olxbr/code-quality-action@v1
